sudo: false

language: python

addons:
  postgresql: "9.4"
  apt:
    packages:
      - postgresql-plpython-9.4
      - liblapack-dev
      - libatlas-dev
      - gfortran

env:
  - PGUSER=postgres

before_script: make install

script: make test
