dist: xenial
language: c
sudo: required

env:
  global:
    - PAGER=cat
    - PGUSER=postgres
    - PGDATABASE=postgres
    - PGOPTIONS='-c client_min_messages=NOTICE'
    - PGPORT=5432
    - POSTGIS_VERSION="2.5"

jobs:
  include:
    - env: POSTGRESQL_VERSION="9.6" POSTGIS_VERSION="2.5"
    - env: POSTGRESQL_VERSION="10" POSTGIS_VERSION="2.5"
    - env: POSTGRESQL_VERSION="11" POSTGIS_VERSION="2.5"
    - env: POSTGRESQL_VERSION="12" POSTGIS_VERSION="2.5"
    - env: POSTGRESQL_VERSION="12" POSTGIS_VERSION="3"
  allow_failures:
    - env: POSTGRESQL_VERSION="12" POSTGIS_VERSION="2.5"
    - env: POSTGRESQL_VERSION="12" POSTGIS_VERSION="3"

before_install:

  - sudo service postgresql stop;
  - sudo apt-get remove postgresql* -y
  - sudo apt-get install -y --allow-unauthenticated --no-install-recommends --no-install-suggests postgresql-$POSTGRESQL_VERSION postgresql-client-$POSTGRESQL_VERSION postgresql-server-dev-$POSTGRESQL_VERSION postgresql-common
  - sudo apt-get install -y --allow-unauthenticated postgresql-$POSTGRESQL_VERSION-postgis-$POSTGIS_VERSION postgresql-$POSTGRESQL_VERSION-postgis-$POSTGIS_VERSION-scripts postgis

  # For pre12, install plpython2. For PG12 install plpython3
  - if [[ $POSTGRESQL_VERSION != '12' ]]; then sudo apt-get install -y postgresql-plpython-$POSTGRESQL_VERSION python python-pip python-software-properties python-joblib python-nose python-setuptools; else sudo apt-get install -y postgresql-plpython3-12 python3 python3-pip python3-software-properties python3-joblib python3-nose python3-setuptools; fi;

  - sudo pg_dropcluster --stop $POSTGRESQL_VERSION main
  - sudo rm -rf /etc/postgresql/$POSTGRESQL_VERSION /var/lib/postgresql/$POSTGRESQL_VERSION
  - sudo pg_createcluster -u postgres $POSTGRESQL_VERSION main -- -A trust
  - sudo /etc/init.d/postgresql start $POSTGRESQL_VERSION || sudo journalctl -xe

install:
  - sudo make install

script:
  - make test
  - ./check-compatibility.sh

after_failure:
  - pg_lsclusters
  - cat src/pg/test/regression.diffs
