sudo: false

language: python
python:
  - 2.7

addons:
  postgresql: "9.4"
  apt:
    packages:
      - postgresql-plpython-9.4
      - postgresql-server-dev-9.4
      - liblapack-dev
      - libatlas-dev
      - gfortran

env:
  - PGUSER=postgres

# From https://gist.github.com/dan-blanchard/7045057
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p `pwd`/miniconda
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy pysal scikit-learn
  - make install

script: make test
