sudo: false

language: python

addons:
  postgresql: "9.4"
  apt:
    packages:
      - postgresql-plpython-9.4
      - liblapack-dev
      - libatlas-dev
      - gfortran

env:
  - PGUSER=postgres

before_script:
  - pip install numpy==1.11.0
  - pip install scipy==0.17.1
  - make install

script: make test
